version: '3.9'

services:
  mycartoonboxbackend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html/mycartoonboxbackend
    networks:
      - db_my_cartoonbox_backend
networks:
  db_my_cartoonbox_backend: